apiVersion: v1
kind: Pod
metadata:
  name: sample11
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:  #Min
        memory: "64Mi"
        cpu: "250m"
      limits:   #on availability only
        memory: "128Mi"
        cpu: "500m"

## 1 cpu = 1000m
#